### ISSUE TITLE
Certain views not adhering to TV/Movie ratings

### ISSUE THREAD

**Issue by mattmcspirit** [Larrikinau/overseerr-content-filtering#13]
### Description

Hey - I've been doing some more testing, and have found the following. For my test case, I created a dedicated 'Test User', local to Overseerr, but have replicated the same with a user imported from Plex.

Firstly, I tested filtering content with 0 votes, 0 rating, and no restrictions on TV/Movie rating (Y, G R etc). Everything seemed to work fine.

Then, I set these settings:

<img width="743" height="858" alt="Image" src="https://github.com/user-attachments/assets/6454b470-e4c1-4cf8-8261-55b550924fb2" />

**Issue 1** - Straight off the bat, on the **Discover** landing page, the **Trending** list doesn't seem to adhere to the rating setting, with plenty of 'R" rated content shown.

<img width="1412" height="421" alt="Image" src="https://github.com/user-attachments/assets/a126d7d3-6094-4498-b56b-6857762ffcef" />

**Working** - From there, going into Movies, and/or Series from the left nav, does seem to apply the correct filters. The same appears to be true when navigating to some of the other links on the Discover page, such as Popular Movies, Popular Series and Genre's.

**Issue 2** - The **Studios** and the **Networks** filters do not seem to be adhering to the ratings - for instance, here's HBO (Remember, rating set to G and TV-Y):

<img width="1654" height="511" alt="Image" src="https://github.com/user-attachments/assets/32d0f032-e16c-4f16-ad3b-26df40ca9e3e" />

**Working** - Search results seem to be working OK - you just tend to get results for unrated stuff, but I'll consider a feature request for that!

**Issue 3** - From the **Discover** page, ignoring Trending, if I select a filtered (by rating) movie, such as Disney Villains Unite:

<img width="834" height="753" alt="Image" src="https://github.com/user-attachments/assets/e2630189-6ffd-40e8-9146-8a02083ff4b0" />

Once clicked on, if I scroll down, within that particular item, I'm getting recommendations that aren't filtered:

<img width="913" height="1200" alt="Image" src="https://github.com/user-attachments/assets/bbd71382-64ae-48b8-a95e-ffccfc12fa40" />

The same is true for **Similar Titles**. When clicking on the movie "Wall-E", I see the following:

<img width="2500" height="1249" alt="Image" src="https://github.com/user-attachments/assets/d5b2cede-9b80-46ba-ac4d-1ce6e12f8688" />

Many of these **Similar Titles** are either unrated, and therefore slip through the net, or are higher rated (Death Race 2050 is an R rating).

I hope that helps! Seems like applying the filters that are working on certain sections, to those additional sections (trending, recommendations, similar titles) would be great. Adding a tick-box option in your filters to hide movies/shows without a rating, could also be a valuable option?

Thanks so much!

### Version

1.4.1

### Steps to Reproduce

See above.

### Logs

```shell

```

### Platform

desktop

### Device

Browser (PC), IOS

### Operating System

Windows 11, IOS 18

### Browser

Edge, Safari

### Code of Conduct

- [x] I agree to follow Overseerr's Code of Conduct

**Comment by Larrikinau** [comment]
I'm currently away on vacation, but I am back next week. Let me look into this and fix it then. Thanks for bringing it to my attention!

**Comment by mattmcspirit** [comment]
No rush at all! Hopefully it's just a case of applying the same filters to those other sections! Please let me know if you ever want me to test any early releases etc.

Have a great trip!

**Comment by daveeeh** [comment]
just to confirm (as requested in other issue) I do see similar results to @mattmcspirit with trending and related showing items which are outside the user's settings

**Comment by Larrikinau** [comment]
This should now be fixed. Would you mind upgrading to the latest docker release and letting me know? Thanks!

**Comment by mattmcspirit** [comment]
I'll give this a bash over the next few days - thank you!

**Comment by mattmcspirit** [comment]
OK, gave it a bash now instead! Install 1.4.2 successfully.

**Fixed**: Studios and Genres (Movies and Series)
**Not fixed**: Trending, and Recommendations/Similar Titles when viewing a particular movie/TV show

Trending:

<img width="2548" height="1275" alt="Image" src="https://github.com/user-attachments/assets/b5354be6-f2e4-442b-a96f-20122ff2d0d1" />

Recommendations/Similar Titles:

<img width="2545" height="1270" alt="Image" src="https://github.com/user-attachments/assets/6e1beb4a-d487-4f37-805c-8ddc6b583587" />

Thanks for the continued work here!

**Comment by Larrikinau** [comment]
> OK, gave it a bash now instead! Install 1.4.2 successfully.

> Thanks for the continued work here!

I believe I have addressed the remaining bugs. Thanks for testing it for me.  I've also actually done a major upgrade to the code base to incorporate the latest changes that Overseerr have done so we are in sync with their latest release.

Please let me know how you get on.

**Comment by mattmcspirit** [comment]
Hey - thank you. I updated to 1.5.0, but unfortunately it seems to be the same for trending, and Recommendations/Similar Titles when viewing a particular movie/TV show.

Should I be clearing a cache, or resetting a database somewhere? I'm just reinstalling the docker container, but I'm not sure if it's got stale data somewhere, so please let me know if there are extra steps to clean up before redeploying the container. Trending is showing all ratings, and no change in the recommended/similar titles when viewing a particular show/movie.

<img width="2544" height="1277" alt="Image" src="https://github.com/user-attachments/assets/c885fe8f-7f60-4eb9-8c41-3c51256fcdac" />

Thanks!
Matt

**Comment by mattmcspirit** [comment]
Did you retract the 1.5.1? I saw an email with a comment about that, but it seems to have gone? I did a redeployment of the container, but it's showing as 1.5.0. This could just be me and my inexperience!

Thanks!

**Comment by mattmcspirit** [comment]
I adjusted the container redeployment to use 1.5.1 as the tag, but it seems some bits are being a bit quirky - I'm seeing empty sections (Trending, Popular Movies etc) for my main, unfiltered user.

Should I just revert to "latest" for now?

**Comment by Larrikinau** [comment]
1.5.1 was pulled due to bugs so I deleted the comment.  1.5.2 is now released and I believe this time it is fixed (along with some other bug fixes).  Never peg a docker version - always use latest and that way you can't get a non production version.

This took longer than I thought as I wanted to ensure it really worked in a test environment plus I actually added some additional functionality and fixed a couple of other bugs.

Let me know how you go! :)

**Comment by mattmcspirit** [comment]
**Filtering**

Getting closer! :)

I'd say all of the main views now, including trending etc, are filtered!

One area I forgot to mention, was search - it seems that search results have some strange things in:

<img width="2544" height="1271" alt="Image" src="https://github.com/user-attachments/assets/0579396a-85c8-4d32-81cc-7fb167786144" />

I searched for "terminator" on my restricted user, and got a mix of TV-MA, NR, some movies without a rating or NR at all.

Also, the country filtering may not have been applied either - I was testing with US and English as country and language, but I'm not quite sure the results are adhering to those filters.

**Other comments**
One other strange thing I did notice, and this was also on my main user (with no filters applied), is the difference in returned results compared with the 1.34 Overseerr. So, with these settings as my main user:

<img width="747" height="559" alt="Image" src="https://github.com/user-attachments/assets/40dab5ae-3114-411e-9b05-989553d82e9c" />

- The results for Trending and Popular Movies are very similar:

<img width="2338" height="504" alt="Image" src="https://github.com/user-attachments/assets/af26a11b-c92d-4c85-90fc-12c1c0a9ff2e" />

- And, when clicking into say, Netflix, or Disney, the results seem capped at 40 and some of the Movie Studios like 20th Century seem lower than you'd expect. Again, this is with my main user, with no restrictions (apart from adult) as shown above.

However, when I flip over to 1.34:

Noticeable differences between Trending and Popular (this isn't such a big deal, but wanted to mention it anyway)

<img width="2341" height="500" alt="Image" src="https://github.com/user-attachments/assets/9ccd4cc3-2b3d-4472-8774-7e9a775d051a" />

But when I open something like Netflix:

<img width="2528" height="1283" alt="Image" src="https://github.com/user-attachments/assets/1dd63877-428d-4913-b001-7876cbd5e127" />

The returned results are significantly greater - again, this is for my main user, who doesn't have filters applied apart from adult.

Should I be seeing this difference?

Thanks!
Matt

**Comment by Larrikinau** [comment]
All your issues should now be fixed. If you put a rating on a user, then it will block NR.

In relation as to why you get different results or not as many titles from the original overseer, that's because I've put a default of 3000 votes and a rating of 6 for it to show. Basically filtering out stuff that no one has voted on and/or rates poorly.  You can easily change those and make it 1 and 1 and you'll get the same results as the original Overseerr sans Adult material.

So I think we are finally there!

**Comment by Larrikinau** [comment]
Awaiting confirmation issue can be closed.

**Comment by mattmcspirit** [comment]
> All your issues should now be fixed. If you put a rating on a user, then it will block NR.
> 
> In relation as to why you get different results or not as many titles from the original overseer, that's because I've put a default of 3000 votes and a rating of 6 for it to show. Basically filtering out stuff that no one has voted on and/or rates poorly. You can easily change those and make it 1 and 1 and you'll get the same results as the original Overseerr sans Adult material.
> 
> So I think we are finally there!

So, something still isn't quite right - check out this screen recording to see what I see (the same results with votes set to 0 and 0, or 1 and 1:

https://1drv.ms/v/c/301a5eef2b4ba542/EQjWMjZHxRtMpI14IKCWjCcBASWZmGJha3a3Y6aSAMmNrg?e=sXO3cY

Could it be to do with the use of my TMDB API key versus what's native to the core 1.34 version?

**Comment by mattmcspirit** [comment]
@daveeeh - do you see the same as me in this video? https://1drv.ms/v/c/301a5eef2b4ba542/EQjWMjZHxRtMpI14IKCWjCcBASWZmGJha3a3Y6aSAMmNrg?e=sXO3cY

If you have a user without any restrictions set, and 0 set for votes/ratings, when you select a streaming provider like Netflix or HBO, are you seeing a small number of results?
