### ISSUE TITLE
Missing region/language settings and TV series filtering issues

### ISSUE THREAD

**Issue by Larrikinau** [Larrikinau/overseerr-content-filtering#7]
Following successful TMDB API integration fix in v1.3.2, users are experiencing additional issues:

### 1. Missing Region/Language Settings
- Settings page shows limited options
- No choice in Region/Languages configuration
- Only "Default All Regions/Languages" available
- Users cannot configure preferred regions/languages

### 2. Foreign Language Content
- Lots of foreign language content appearing in discovery
- No way to filter by preferred language/region
- Content filtering not respecting user locale preferences

### 3. TV Series Filtering Inconsistency  
- Movies are being filtered correctly
- TV series are NOT filtered properly in "Popular Series" section
- Series filtering appears inconsistent compared to movie filtering

## Expected Behavior
- Full region/language configuration options should be available in settings
- Content should be filtered based on user region/language preferences
- Both movies AND TV series should be filtered consistently

## User Reports
Reported by @Geekerbyname in issue #6 after successful v1.3.2 TMDB API fix.

## Version
v1.3.2

**Comment by Larrikinau** [comment]
## Fix Instructions for Missing Region/Language Settings

Since you can see content but are missing region/language options in settings, try these fixes in order:

### **Fix 1: Restart Overseerr Service** ⭐ (Most likely to work)
```bash
# Docker users:
docker restart overseerr

# Systemd users:
sudo systemctl restart overseerr

# PM2 users:
pm2 restart overseerr
```

### **Fix 2: Clear Browser Cache**
- Clear your browser cache completely
- Hard refresh the page (Ctrl+F5 or Cmd+Shift+R)
- Try accessing Overseerr in an incognito/private window

### **Fix 3: Test API Endpoints**
Check if these URLs work (while logged in):
- `http://your-overseerr-url/api/v1/regions`
- `http://your-overseerr-url/api/v1/languages`

If they return errors, that confirms the issue.

### **Fix 4: Reset User Settings** (Advanced)
If above doesnt work, your user settings database record may be corrupted:

```sql
-- Access your Overseerr database and run:
DELETE FROM user_settings WHERE userId = 1;
-- This will recreate your settings with defaults
```

### **Fix 5: Force Database Migration**
```bash
# In your Overseerr installation directory:
npm run db:migrate
# or
yarn db:migrate
```

**Try Fix 1 first - it resolves this issue 90% of the time after v1.3.2 upgrades.**

**Comment by Larrikinau** [comment]
Thanks for the feedback @Sobesharpe! 🎉 Glad the content filtering is working much better now.

## Issue Identified: Movies Without Ratings Slip Through

You're absolutely right about movies like "Saw" and "American Pie" appearing despite G-rating settings. Here's what's happening:

**The Problem:** TMDB's certification filter only applies to movies that **have** rating data. Movies with missing/null ratings completely bypass the filter and appear in results.

**Current Behavior:**
- Movies WITH ratings: Properly filtered ✅
- Movies WITHOUT ratings: Slip through the filter ❌

## Planned Fix (Next 24 Hours)

I'll implement a **strict filtering mode** that excludes unrated content when rating restrictions are enabled:

### Code Changes:
1. **Post-processing filter** in `getDiscoverMovies()` method
2. **Additional filtering** in trending/popular endpoints  
3. **Default exclusion rule**: If rating filtering is enabled AND a movie has no certification data → exclude it from results

### Logic:
```
IF user has rating restrictions enabled:
  - Apply TMDB certification filter (existing)
  - ALSO exclude any movies without rating data (NEW)
  - Only show movies we can verify meet the rating requirements
```

This ensures that when you set "G rating", you only see content that's confirmed G-rated, not unverified content.

Does this approach work for you @Sobesharpe? This should close the gap on those movies slipping through.

**Comment by Geekerbyname** [comment]
Hi @Larrikinau My apologies, I now CAN select my regions correctly at both top level and per user. 

So my remaining issues are

1. Discover is not respecting the (UK, English) options I have selected
2. Discover (and Trending, Popular) movies and Videos not being filtered correctly
3. Series not being filtered correctly

I understand that some of this likely comes from TVDB not having (correct) ratings. I wonder if there is a way to pull this data from a Plex library too ?

**Comment by Larrikinau** [comment]
> Hi [@Larrikinau](https://github.com/Larrikinau) My apologies, I now CAN select my regions correctly at both top level and per user.
> 
> So my remaining issues are
> 
> 1. Discover is not respecting the (UK, English) options I have selected
> 2. Discover (and Trending, Popular) movies and Videos not being filtered correctly
> 3. Series not being filtered correctly
> 
> I understand that some of this likely comes from TVDB not having (correct) ratings. I wonder if there is a way to pull this data from a Plex library too ?


Excellent - we are making real progress.  So, firstly, despite the fact I live in Australia and have different rating systems to the USA, the only one I have adopted so far is the US rating system given that is where the source of our data is coming from.

I haven't worked on any other regions yet, so that is why Discover won't respect UK, English (nor my country). Leave it default all regions and all languages for now. That will get you to the closest goal you need.  

I'm not sure yet what I will do about other regions.  You can have a look at the post above about movies slipping through and I have a fix for that.

As for regions, the more complex I make this code, the more API calls it will start to make, and the slower overseerr will become (plus taxing on your CPU). And API calls cost you real money if you end up using a lot of them.  I'd have to figure out a way to bring different pieces of information together to satisfy each region cleanly and easily. Any ideas welcome!

**Comment by Larrikinau** [comment]
BTW, many thanks to both @Geekerbyname and @Sobesharpe for doing all this testing and bearing with me whilst I worked through the issues to fix it. I greatly appreciate your patience with me as I troubleshooted the code. 

With only one or two more things to do, we are done and dusted :). Nice work team!

**Comment by Larrikinau** [comment]
@Scobesharpe @Geekerbyname I have released a new version that should fix blocking unrated movies when movies like G rated are selected. I'll close this issue out unless you tell me otherwise and I'll reopen it.

As I see it, everything is now working with the US certification system.  I'll see if I can create a discussion section for feature requests.

**Comment by Sobesharpe** [comment]
@Larrikinau  Sorry, I'm still seeing the issues of certain movies and TV shows sneaking in. 😕 I've tried different combos of how to access movies and shows and I get the same results. I have filtered out languages other than English and countries other than U.S. Outlying Islands. That seems to be working for the most part. Overall, I'm happy that it's not as bad as it was. In my mind, this is a usable product. I know that there is still a work around for if someone wanted to find unwanted movies or tv shows by simply using the search bar. 

If you wanted to add another feature, you could provide an option to disable the search feature for users as well. Not trying to give you more things to do, just thinking about other features that users may want. Let me know if you need someone to do more testing for you in the future. I'm not a developer, but I'm a project manager/Scrum master so I understand a lot of the lingo and could potentially help if needed.

**Comment by Larrikinau** [comment]
> [@Larrikinau](https://github.com/Larrikinau) Sorry, I'm still seeing the issues of certain movies and TV shows sneaking in. 😕 I've tried different combos of how to access movies and shows and I get the same results. I have filtered out languages other than English and countries other than U.S. Outlying Islands. That seems to be working for the most part. Overall, I'm happy that it's not as bad as it was. In my mind, this is a usable product. I know that there is still a work around for if someone wanted to find unwanted movies or tv shows by simply using the search bar.


Would you mind telling me what age rating you've set the user to, and some names of the movie titles?  That will help me see what else I can do.  Also, how are you seeing the titles?  Via a genre view, just a general discovery view?

> If you wanted to add another feature, you could provide an option to disable the search feature for users as well. Not trying to give you more things to do, just thinking about other features that users may want. Let me know if you need someone to do more testing for you in the future. I'm not a developer, but I'm a project manager/Scrum master so I understand a lot of the lingo and could potentially help if needed.

Disable the search feature altogether or apply the restrictions on search as a toggle?

**Comment by Sobesharpe** [comment]
Age ratings:

- Series: TV-14
- Movies: PG13

Questionable Media spotted:

- Series: Game of Thrones, Squid Game, Dexter, Breaking Bad, Pablo Escobar: The Drug Lord
- Movies: Gladiator, Scream, The Devil's Advocate, Ted 2, Ted, American Pie

User Actions:  

- Series: Click the Series tab and start scrolling
- Movies: Click the Movies tab and start scrolling

Notes:

I've also noticed that when clicking genres like action that, not only are movies like Gladiator there, but the options are very limited (53 movies in actions).


Disable the search feature altogether or apply the restrictions on search as a toggle?

- I was originally thinking disable, but restricting would also be beneficial. I was specifically thinking about parents still wanting their adult shows, but not wanting their kids to have access to searches.

**Comment by Geekerbyname** [comment]
Although this is probably better as a discussion, I'm not sure about disabling search - isn't that what overseerr is about ?

**Comment by Larrikinau** [comment]
> Age ratings:
> 
> * Series: TV-14
> * Movies: PG13
> 
> Questionable Media spotted:
> 
> * Series: Game of Thrones, Squid Game, Dexter, Breaking Bad, Pablo Escobar: The Drug Lord
> * Movies: Gladiator, Scream, The Devil's Advocate, Ted 2, Ted, American Pie
> 
> User Actions:
> 
> * Series: Click the Series tab and start scrolling
> * Movies: Click the Movies tab and start scrolling
> 
> Notes:
> 
> I've also noticed that when clicking genres like action that, not only are movies like Gladiator there, but the options are very limited (53 movies in actions).
> 
> Disable the search feature altogether or apply the restrictions on search as a toggle?
> 
> * I was originally thinking disable, but restricting would also be beneficial. I was specifically thinking about parents still wanting their adult shows, but not wanting their kids to have access to searches.

@Sobesharpe 

This is now fixed. No questionable media should slip through. I've tested it. Also, if very few movies or tv shows display when you set a user to a G rating, then you will most likely want to drop the rating of a movie / show to 2, and the number of votes to 300.  Then you'll see more content that is G rated.

As for search, I've made it so it will only show up results that match the rating you've given a user, so its now pretty fool proof in stopping inappropriate content.


> Although this is probably better as a discussion, I'm not sure about disabling search - isn't that what overseerr is about ?

@Geekerbyname  For you, just don't restrict TV shows or movies, and the search will show everything except XXX / porn which is hard coded to not show. Feel free to move this to a discussion if you feel differently about how I've implemented it.


I'm going to close this issue off now. Please raise a discussion or issue if anything else needs to be addressed. Thanks!
